### PR TITLE
added titles attribute

### PR DESCRIPTION
**Pull request by whamtet**
Thanks for the great library Belka!  I needed html titles on the day cells so I've added this small change, thought you might appreciate.

Matt

### CODE REVIEW

**Comment by GiovanniFrigo** [comment]
Thanks Matt! A simple change that could be useful for others. Merging now!

**Comment by whamtet** [comment]
Thanks!

**Comment by whamtet** [comment]
@GiovanniFrigo do you mind deploying latest version to NPM?

**Comment by GiovanniFrigo** [comment]
deployed now. you'll find it in version 1.2.5

**Comment by whamtet** [comment]
Thankyou sir!!!

**Pull request merged**
